version: '3.4'

services:
  web:
    container_name: hotspots-api 
    image: hotspots-api:${IMAGE_TAG}
    restart: always
    ports:
      - ${PORT}:8000
    # volumes:
      # - ./logs:/home/appuser/hotspots-api/logs
    environment:
      - POSTGRES_USER=${POSTGRES_USER}  
      - POSTGRES_PW=${POSTGRES_PW}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - backend

networks: 
    backend:
