version: '3.4'

services:
  web:
    container_name: visualizer
    image: visualizer:${IMAGE_TAG}
    restart: always
    ports:
      - ${VISUALIZER_PORT}:5000
    volumes:
      - ./logs:/home/appuser/visualizer/logs
    environment:
      - API_URL_BASE=${API_URL_BASE}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - backend

networks: 
    backend:
