version: '3.4'

services:
  web:
    container_name: fire_visualizer_testing
    image: ${IMG_REPO_URL}fire_visualizer:${IMAGE_TAG}
    restart: always
    ports:
      - ${PORT}:5000
    volumes:
      - ./logs:/home/appuser/visualizer/logs
    environment:
      - API_URL_BASE=${EXT_API_URL_BASE}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - backend

networks: 
    backend:
